-- MySQL Script generated by MySQL Workbench
-- Mon May  2 22:51:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema petcam
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema petcam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `petcam` DEFAULT CHARACTER SET utf8 ;
USE `petcam` ;

-- -----------------------------------------------------
-- Table `petcam`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcam`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `sexo` CHAR(1) NULL,
  `status` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `nome_usuario_UNIQUE` (`nome_usuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petcam`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcam`.`animal` (
  `id_animal` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `nome` VARCHAR(200) NULL,
  `raca` VARCHAR(45) NOT NULL,
  `cor` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  `sexo` CHAR(1) NOT NULL,
  `status` CHAR(1) NULL,
  PRIMARY KEY (`id_animal`),
  INDEX `fk_animal_cliente1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_animal_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `petcam`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petcam`.`petshop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcam`.`petshop` (
  `id_petshop` INT NOT NULL AUTO_INCREMENT,
  `nome_fantasia` VARCHAR(200) NOT NULL,
  `status` CHAR(1) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `nome_usuario` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_petshop`),
  UNIQUE INDEX `nome_usuario_UNIQUE` (`nome_usuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petcam`.`Camera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcam`.`Camera` (
  `id_camera` INT NOT NULL AUTO_INCREMENT,
  `id_petshop` INT NOT NULL,
  `ip` VARCHAR(15) NOT NULL,
  `porta` VARCHAR(4) NOT NULL,
  `status` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_camera`),
  UNIQUE INDEX `ip_UNIQUE` (`ip` ASC) VISIBLE,
  INDEX `fk_Camera_petshop1_idx` (`id_petshop` ASC) VISIBLE,
  CONSTRAINT `fk_Camera_petshop1`
    FOREIGN KEY (`id_petshop`)
    REFERENCES `petcam`.`petshop` (`id_petshop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petcam`.`acesso_camera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcam`.`acesso_camera` (
  `id_acesso_camera` INT NOT NULL AUTO_INCREMENT,
  `id_petshop` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `status` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_acesso_camera`),
  INDEX `fk_acesso_camera_petshop1_idx` (`id_petshop` ASC) VISIBLE,
  INDEX `fk_acesso_camera_cliente1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_acesso_camera_petshop1`
    FOREIGN KEY (`id_petshop`)
    REFERENCES `petcam`.`petshop` (`id_petshop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acesso_camera_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `petcam`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `petcam`.`monitoramento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `petcam`.`monitoramento` (
  `id_monitoramento` INT NOT NULL AUTO_INCREMENT,
  `id_acesso_camera` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_animal` INT NOT NULL,
  `id_camera` INT NOT NULL,
  PRIMARY KEY (`id_monitoramento`),
  INDEX `fk_monitoramento_acesso_camera1_idx` (`id_acesso_camera` ASC) VISIBLE,
  INDEX `fk_monitoramento_animal1_idx` (`id_animal` ASC) VISIBLE,
  INDEX `fk_monitoramento_Camera1_idx` (`id_camera` ASC) VISIBLE,
  CONSTRAINT `fk_monitoramento_acesso_camera1`
    FOREIGN KEY (`id_acesso_camera`)
    REFERENCES `petcam`.`acesso_camera` (`id_acesso_camera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monitoramento_animal1`
    FOREIGN KEY (`id_animal`)
    REFERENCES `petcam`.`animal` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_monitoramento_Camera1`
    FOREIGN KEY (`id_camera`)
    REFERENCES `petcam`.`Camera` (`id_camera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
